//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SAO.DevHelper.Config.Config
{

    public partial class Application : XPObject
    {
        string fName;
        [Indexed(Name = @"Name", Unique = true)]
        [DevExpress.Xpo.DisplayName(@"名称")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fCaption;
        [DevExpress.Xpo.DisplayName(@"标题")]
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>("Caption", ref fCaption, value); }
        }
        string fSkin;
        [DevExpress.Xpo.DisplayName(@"皮肤")]
        public string Skin
        {
            get { return fSkin; }
            set { SetPropertyValue<string>("Skin", ref fSkin, value); }
        }
        string fYears;
        [DevExpress.Xpo.DisplayName(@"版权年份")]
        public string Years
        {
            get { return fYears; }
            set { SetPropertyValue<string>("Years", ref fYears, value); }
        }
    }

}
